slurmstepd: error: Unable to create TMPDIR [/tmp/siw001/874536]: No such file or directory
slurmstepd: error: Setting TMPDIR to /tmp
Traceback (most recent call last):
  File "/fs/hestia_Heccc/rpnatm/siw001/gef/./main_gef.py", line 271, in <module>
    rank = main(args)
  File "/fs/hestia_Heccc/rpnatm/siw001/gef/./main_gef.py", line 80, in main
    Q = stepper.step(Q, param.dt)
  File "/fs/hestia_Heccc/rpnatm/siw001/gef/integrators/integrator.py", line 56, in step
    result = self.__step__(Q, dt)
  File "/fs/hestia_Heccc/rpnatm/siw001/gef/integrators/epi.py", line 103, in __step__
    print(f'EXODE converged at iteration {stats[0]}, with {stats[1]} rejected steps to a solution with local error {stats[4]:.2e}')
IndexError: tuple index out of range
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 42599 ON ib18be-054 CANCELLED AT 2024-01-18T02:43:48 ***
slurmstepd: error: *** STEP 42599.1 ON ib18be-054 CANCELLED AT 2024-01-18T02:43:48 ***
